// <auto-generated />
using System;
using ForeverBloom.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ForeverBloom.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "ltree");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ForeverBloom.Domain.Catalog.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(6)
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentSlug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("current_slug");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasPrecision(6)
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("name");

                    b.Property<long?>("ParentCategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_category_id");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("ltree")
                        .HasColumnName("path");

                    b.Property<int>("PublishStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("publish_status");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasPrecision(6)
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("ParentCategoryId")
                        .HasDatabaseName("ix_categories_parent_category_id");

                    b.HasIndex("Path")
                        .HasDatabaseName("ix_categories_path");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Path"), "gist");

                    b.HasIndex("Name", "ParentCategoryId")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_name_parent_category_id");

                    b.HasIndex("PublishStatus", "DisplayOrder")
                        .HasDatabaseName("ix_categories_publish_status_display_order");

                    b.HasIndex("ParentCategoryId", "PublishStatus", "DisplayOrder")
                        .HasDatabaseName("ix_categories_parent_category_id_publish_status_display_order");

                    b.ToTable("categories", null, t =>
                        {
                            t.HasCheckConstraint("ck_categories_current_slug_format", "\"current_slug\" ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'");

                            t.HasCheckConstraint("ck_categories_path_segments", "nlevel(\"path\") <= 10");

                            t.HasCheckConstraint("ck_categories_publish_status_valid_codes", "\"publish_status\" IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("ForeverBloom.Domain.Catalog.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Availability")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(6)
                        .HasColumnName("availability");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(6)
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentSlug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("current_slug");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasPrecision(6)
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<string>("FullDescription")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("full_description");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean")
                        .HasColumnName("is_featured");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("meta_description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<decimal?>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("price");

                    b.Property<int>("PublishStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("publish_status");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("SeoTitle")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("seo_title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasPrecision(6)
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_products_category_id");

                    b.HasIndex("CategoryId", "PublishStatus", "DisplayOrder")
                        .HasDatabaseName("ix_products_category_id_publish_status_display_order");

                    b.ToTable("products", null, t =>
                        {
                            t.HasCheckConstraint("ck_products_availability_valid_codes", "\"availability\" IN (1, 2, 3, 5, 6)");

                            t.HasCheckConstraint("ck_products_current_slug_format", "\"current_slug\" ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'");

                            t.HasCheckConstraint("ck_products_price_positive", "\"price\" > 0");

                            t.HasCheckConstraint("ck_products_publish_status_valid_codes", "\"publish_status\" IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("ForeverBloom.Persistence.SlugRegistry.SlugRegistration", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<int>("EntityType")
                        .HasColumnType("integer")
                        .HasColumnName("entity_type");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_slug_registry");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_slug_registry_is_active");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_slug_registry_slug");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_slug_registry_entity_type_entity_id");

                    b.HasIndex("EntityType", "EntityId", "IsActive")
                        .IsUnique()
                        .HasDatabaseName("ix_slug_registry_entity_type_entity_id_is_active")
                        .HasFilter("\"is_active\" = true");

                    b.ToTable("slug_registry", null, t =>
                        {
                            t.HasCheckConstraint("ck_slug_registry_entity_type_valid_codes", "\"entity_type\" IN (1, 2)");

                            t.HasCheckConstraint("ck_slug_registry_slug_format", "\"slug\" ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'");
                        });
                });

            modelBuilder.Entity("ForeverBloom.Domain.Catalog.Category", b =>
                {
                    b.HasOne("ForeverBloom.Domain.Catalog.Category", "ParentCategory")
                        .WithMany("ChildCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_categories_categories_parent_category_id");

                    b.OwnsOne("ForeverBloom.Domain.Catalog.Image", "Image", b1 =>
                        {
                            b1.Property<long>("CategoryId")
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            b1.Property<string>("AltText")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("image_alt_text");

                            b1.Property<string>("Source")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("image_path");

                            b1.HasKey("CategoryId");

                            b1.ToTable("categories");

                            b1.WithOwner()
                                .HasForeignKey("CategoryId")
                                .HasConstraintName("fk_categories_categories_id");
                        });

                    b.Navigation("Image");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("ForeverBloom.Domain.Catalog.Product", b =>
                {
                    b.HasOne("ForeverBloom.Domain.Catalog.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_products_categories_category_id");

                    b.OwnsMany("ForeverBloom.Domain.Catalog.ProductImage", "Images", b1 =>
                        {
                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<long>("Id"));

                            b1.Property<int>("DisplayOrder")
                                .HasColumnType("integer")
                                .HasColumnName("display_order");

                            b1.Property<bool>("IsPrimary")
                                .HasColumnType("boolean")
                                .HasColumnName("is_primary");

                            b1.Property<long>("ProductId")
                                .HasColumnType("bigint")
                                .HasColumnName("product_id");

                            b1.HasKey("Id")
                                .HasName("pk_product_images");

                            b1.HasIndex("ProductId")
                                .IsUnique()
                                .HasDatabaseName("ix_product_images_product_id")
                                .HasFilter("is_primary = true");

                            b1.HasIndex("ProductId", "DisplayOrder")
                                .HasDatabaseName("ix_product_images_product_id_display_order");

                            b1.ToTable("product_images", (string)null);

                            b1.WithOwner("Product")
                                .HasForeignKey("ProductId")
                                .HasConstraintName("fk_product_images_products_product_id");

                            b1.OwnsOne("ForeverBloom.Domain.Catalog.Image", "Image", b2 =>
                                {
                                    b2.Property<long>("ProductImageId")
                                        .HasColumnType("bigint")
                                        .HasColumnName("id");

                                    b2.Property<string>("AltText")
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)")
                                        .HasColumnName("image_alt_text");

                                    b2.Property<string>("Source")
                                        .IsRequired()
                                        .HasMaxLength(500)
                                        .HasColumnType("character varying(500)")
                                        .HasColumnName("image_path");

                                    b2.HasKey("ProductImageId");

                                    b2.ToTable("product_images");

                                    b2.WithOwner()
                                        .HasForeignKey("ProductImageId")
                                        .HasConstraintName("fk_product_images_product_images_id");
                                });

                            b1.Navigation("Image")
                                .IsRequired();

                            b1.Navigation("Product");
                        });

                    b.Navigation("Category");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("ForeverBloom.Domain.Catalog.Category", b =>
                {
                    b.Navigation("ChildCategories");

                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
